### ISSUE TITLE
Workflow and inherited entities

### ISSUE THREAD

**Issue by danaki** [yokai-php/sonata-workflow#3]
Hello, I'm getting "An exception has been thrown during the rendering of a template ("unable to find the route `admin.verification.workflow_apply_transition`")." and I believe this is sonata-workflow's issue. Here's my setup:

I have an abstract entity:
```
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="verification")
 * @ORM\Entity
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="verification_type", type="string")
 * @ORM\DiscriminatorMap({"personal"="PersonalVerification", "address"="AddressVerification"})
 */
abstract class Verification
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100, nullable=false, unique=true)
     */
    private $status;
}
``` 

and two inherited entities PersonalVerification and AddressVerification.
```
/**
 * @ORM\Table(name="verification_personal")
 * @ORM\Entity
 */
class PersonalVerification extends Verification
{
    // ...
}

/**
 * @ORM\Table(name="verification_address")
 * @ORM\Entity()
 */
class AddressVerification extends Verification
{
    // ...
}
```

My worflow.yaml looks like this:
```
framework:
    workflows:
        verification_state:
            type: 'state_machine'
            places:
                - unverified
                - verified
                - rejected
            initial_place: unverified
            marking_store:
                type: "single_state"
                arguments: ['status']
            supports:
                - App\Entity\Verification
            transitions:
                accept:
                    from: unverified
                    to: verified
                reject:
                    from: unverified
                    to: rejected
```

My sonata_admin.yaml looks like:
```
services:
    admin.verification:
        class: App\Admin\VerificationAdmin
        arguments: [~, App\Entity\Verification, Yokai\SonataWorkflow\Controller\WorkflowController]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Verifications' }
        public: true
        calls:
            - [setSubclasses, [{'Personal': App\Entity\PersonalVerification, 'Address': App\Entity\AddressVerification}]]

    admin.extension.verification_state_workflow:
        class: Yokai\SonataWorkflow\Admin\Extension\WorkflowExtension
        public: true
        arguments:
            - "@workflow.registry"
            - workflow_name: verification_state

    Yokai\SonataWorkflow\Controller\WorkflowController:
        autowire: true
        tags: ['controller.service_arguments']

sonata_admin:
    extensions:
        admin.extension.verification_state_workflow:
            admins:
                - admin.verification
```

I tried to change workflow's "supports" section to:
```
            supports:
                - App\Entity\PersonalVerification
                - App\Entity\AddressVerification
```

It results to successful render of "edit" page but without "transition" dropdown (seems like due to an exception in WorkflowExtension::configureSideMenu() inside getWorkflow() call which is dropped silently). Anyway I think

```
            supports:
                - App\Entity\Verification
```

more correct in this case, because "status" is the state property of the base class.

Thank you.

**Comment by yann-eugone** [comment]
Hello ! Thank you for using this bundle.

I never tried using this extension with inheritance & admin subclasses.

Maybe we can try to get some more information : 
- Did you cleared your cache ?
- Can you see the corresponding route while running `debug:router` command ?
- Did you tried to add some debug information in `Yokai\SonataWorkflow\Admin\Extension\WorkflowExtension` public methods : `dump(__METHOD__);` ?
- Are you sure that there is no place in your code base where that route can be removed (https://sonata-project.org/bundles/admin/master/doc/reference/routing.html#removing-all-routes-except-named-ones for instance) ?

**Comment by yann-eugone** [comment]
Just tried it myself, i have no issue with it.


**In `src/Entity/Verification.php`**

```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="verification")
 * @ORM\Entity
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="verification_type", type="string")
 * @ORM\DiscriminatorMap({"personal"="PersonalVerification", "address"="AddressVerification"})
 */
abstract class Verification
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;
    /**
     * @ORM\Column(type="string", length=100, nullable=false, unique=true)
     */
    private $status;
    public function getId()
    {
        return $this->id;
    }
    public function getStatus()
    {
        return $this->status;
    }
    public function setStatus($status): void
    {
        $this->status = $status;
    }
}
```

**In `src/Entity/AddressVerification.php`**

```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="verification_address")
 * @ORM\Entity
 */
class AddressVerification extends Verification
{
}
```

**In `src/Entity/PersonalVerification.php`**

```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="verification_personal")
 * @ORM\Entity
 */
class PersonalVerification extends Verification
{
}
```

**In `src/Admin/VerificationAdmin.php`**

```php
<?php

namespace App\Admin;

use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Route\RouteCollection;

class VerificationAdmin extends AbstractAdmin
{
    protected function configureRoutes(RouteCollection $collection)
    {
        $collection
            ->remove('create')
            ->remove('delete')
        ;
    }
    protected function configureListFields(ListMapper $list)
    {
        $list
            ->addIdentifier('id')
            ->add('status')
        ;
    }
    protected function configureFormFields(FormMapper $form)
    {
        $form
            ->add('status')
        ;
    }
}
```

**In `config/packages/sonata_admin.yaml`**

```yaml
sonata_admin:
    extensions:
        admin.extension.workflow:
            admins:
                - admin.verification

services:
    admin.verification:
        class: App\Admin\VerificationAdmin
        arguments: [~, App\Entity\Verification, Yokai\SonataWorkflow\Controller\WorkflowController]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Verifications' }
        public: true
        calls:
            - [setSubclasses, [{'Personal': App\Entity\PersonalVerification, 'Address': App\Entity\AddressVerification}]]

    admin.extension.workflow:
        class: Yokai\SonataWorkflow\Admin\Extension\WorkflowExtension
        public: true
        arguments:
            - '@workflow.registry'

    Yokai\SonataWorkflow\Controller\WorkflowController:
        autowire: true
        tags: ['controller.service_arguments']
```

**In `config/packages/workflow.yaml`**

```yaml
framework:
    workflows:
        verification_state:
            type: 'state_machine'
            places:
                - unverified
                - verified
                - rejected
            initial_place: unverified
            marking_store:
                type: "single_state"
                arguments: ['status']
            supports:
                - App\Entity\Verification
            transitions:
                accept:
                    from: unverified
                    to: verified
                reject:
                    from: unverified
                    to: rejected
```

And the result : 

![capture d ecran_2018-09-05_11-47-33](https://user-images.githubusercontent.com/1303838/45085693-9e141500-b101-11e8-898f-9617b8fa9572.png)
