### ISSUE TITLE
Multiple workflow support

### ISSUE THREAD

**Issue by tonyellow** [yokai-php/sonata-workflow#32]
I have multiple workflows configured for some entities. Symfony 4 has support for it, this plugin does not, is that correct? I can not find a way to pass a specific workflow this manager. Thanks in advance!

**Comment by yann-eugone** [comment]
Did you had a look to the `"workflow_name"` option of the extension constructor in [README](https://github.com/yokai-php/sonata-workflow#more-specific-extension-per-admin) ?

When you have multiple workflow on your entities, you cannot register a global extension.
You have to register the extension as many time as you want fore each workflow you want to cover.

Let say you have 2 workflow for your PullRequest entity (`workflow_a` & `workflow_b`), you will end with something like :

```yaml
    admin.extension.pull_request_workflow.workflow_a:
        class: Yokai\SonataWorkflow\Admin\Extension\WorkflowExtension
        public: true
        arguments:
            - '@workflow.registry'
            - workflow_name: workflow_a

    admin.extension.pull_request_workflow.workflow_b:
        class: Yokai\SonataWorkflow\Admin\Extension\WorkflowExtension
        public: true
        arguments:
            - '@workflow.registry'
            - workflow_name: workflow_b

sonata_admin:
    extensions:
        admin.extension.pull_request_workflow.workflow_a:
            admins:
                - admin.pull_request
        admin.extension.pull_request_workflow.workflow_b:
            admins:
                - admin.pull_request
```
