### ISSUE TITLE
Transition item is translated with a "leading" underscore

### ISSUE THREAD

**Issue by gremo** [yokai-php/sonata-workflow#8]
Maybe a minor issue, but the `getLabel` method is missing the `$type` argument:

```php
$menu->addChild(
    $admin->getLabelTranslatorStrategy()->getLabel($transition->getName(), 'workflow'),
    $options
);
```
Which leads to something like:

```yaml
workflow:
    _accept: Accetta
    _reject: Rifiuta
    _submit: Invia
    _suspend: Sospendi
```

What about using "label" or "transition" as `$type` argument?
